export type Article = {
  date: string
  title: string
  source: string
  url: string
  description: string
}

export const APRIL_ARTICLES: Article[] = [
  { date: '2026-04-01', title: 'Samsara to Accelerate the Future of Physical AI at HumanX 2026', source: 'RoboticsTomorrow', url: 'https://www.roboticstomorrow.com/news/2026/03/31/samsara-to-accelerate-the-future-of-physical-ai-at-humanx-2026/26342/', description: 'Samsara announced plans to accelerate physical AI deployment at the HumanX 2026 conference, highlighting real-world AI integration in connected operations.' },
  { date: '2026-04-02', title: 'Anvil Robotics Raises $5.5M to Build "Legos for Robots" Platform for Physical AI Teams', source: 'Crunchbase', url: 'https://news.crunchbase.com/robotics/physical-ai-custom-robot-builder-seed-funding-anvil/', description: 'Anvil Robotics secured $5.5M seed funding to build a modular robot platform. Robots start at $1,900 and the company has delivered over 100 units globally.' },
  { date: '2026-04-03', title: 'Physical AI and Humanoid Robots: Navigating the Convergence of AI and Robotics', source: 'Deloitte', url: 'https://www.deloitte.com/us/en/insights/topics/technology-management/tech-trends/2026/physical-ai-humanoid-robots.html', description: 'Deloitte outlines how physical AI is transforming traditional robots into adaptive machines that can perceive, reason and act in complex real-world environments.' },
  { date: '2026-04-04', title: "Who's Leading The Way In Robotics, Humanoids & Physical AI in 2026", source: 'Raise Summit', url: 'https://www.raisesummit.com/post/robotics-humanoids-physical-ai-leaders', description: 'A comprehensive look at the companies and technologies leading the physical AI and humanoid robotics race in 2026, including NVIDIA, Figure AI, and Boston Dynamics.' },
  { date: '2026-04-05', title: "In Japan, the robot isn't coming for your job — it's filling the one nobody wants", source: 'TechCrunch', url: 'https://techcrunch.com/2026/04/05/japan-is-proving-experimental-physical-ai-is-ready-for-the-real-world/', description: 'Japan is deploying physical AI to fill labor shortages, not replace workers. The government has invested $6.3B targeting 30% of the global physical AI market by 2040.' },
  { date: '2026-04-06', title: 'Robotics & Physical AI: A New Era in Automation', source: 'Global X ETFs', url: 'https://www.globalxetfs.com/articles/robotics-and-physical-ai-a-new-era-in-automation', description: 'Global X analyzes how physical AI is ushering in a new era of automation, with over 500,000 industrial robots installed globally in 2024 and forecasts reaching 700,000 by 2028.' },
  { date: '2026-04-07', title: 'Meet Generalist at the Peak: How Did Qianxun Intelligence Secure $3 Billion in Just 30 Days?', source: '36Kr', url: 'https://eu.36kr.com/en/p/3756066027209477', description: 'Chinese embodied AI startup Qianxun Intelligence completed a new 1 billion yuan financing round led by Shunwei Capital and Yunfeng Capital.' },
  { date: '2026-04-08', title: 'The Physical AI Revolution', source: 'Substack / Paulina Szyzdek', url: 'https://paulinaszyzdek.substack.com/p/the-physical-ai-revolution', description: 'An in-depth analysis of the physical AI revolution, exploring how AI is moving from digital to physical applications and reshaping industries.' },
  { date: '2026-04-09', title: '2026: AI Begins to "Physically Take Root"', source: '36Kr', url: 'https://eu.36kr.com/en/p/3657104242258436', description: 'Physical AI is transitioning from pilot projects to real-world deployments in 2026, with industrial automation and humanoid robots leading adoption.' },
  { date: '2026-04-10', title: 'National Robotics Week — Latest Physical AI Research, Breakthroughs and Resources', source: 'NVIDIA Blog', url: 'https://blogs.nvidia.com/blog/national-robotics-week-2026/', description: 'NVIDIA celebrates National Robotics Week by highlighting Isaac GR00T models, Cosmos world models, Newton 1.0 physics engine, and Isaac Sim 6.0 breakthroughs.' },
  { date: '2026-04-11', title: 'Transforming Asset Management with Physical AI', source: 'The Robot Report', url: 'https://www.therobotreport.com/transforming-asset-management-with-physical-ai/', description: 'Robot Report Podcast Episode 239 with IFS Chief Innovation Officer discusses how physical AI is transforming industrial asset management and maintenance.' },
  { date: '2026-04-12', title: 'Physical AI Set to Transform Robotics, Automation, and Everyday Life', source: 'Technology For You', url: 'https://www.technologyforyou.org/physical-ai-set-to-transform-robotics-automation-and-everyday-life/', description: 'Physical AI is set to fundamentally reshape robotics, industrial automation, and everyday consumer applications through advances in perception and decision-making.' },
  { date: '2026-04-13', title: 'NVIDIA and Global Robotics Leaders Take Physical AI to the Real World', source: 'NVIDIA Newsroom', url: 'https://nvidianews.nvidia.com/news/nvidia-and-global-robotics-leaders-take-physical-ai-to-the-real-world', description: 'NVIDIA partners with ABB Robotics, FANUC, KUKA, Yaskawa and others to deploy physical AI systems across factories, warehouses and industrial environments.' },
  { date: '2026-04-14', title: 'How Physical AI Is Reshaping Robotics Today — and What Comes Next', source: 'BCG', url: 'https://www.bcg.com/publications/2026/how-physical-ai-is-reshaping-robotics-today', description: 'BCG analyzes the uneven progress of physical AI in robotics, with near-term value concentrated in Level 2/3 systems where software-defined perception already transforms economics.' },
  { date: '2026-04-15', title: 'Accenture Invests in General Robotics to Advance Physical AI-Powered Robotics in Manufacturing', source: 'Accenture', url: 'https://newsroom.accenture.com/news/2026/accenture-invests-in-general-robotics-to-advance-physical-ai-powered-robotics-in-manufacturing-and-logistics', description: 'Accenture Ventures invests in General Robotics and its GRID platform, enabling manufacturers and logistics companies to rapidly deploy adaptive robots at scale.' },
  { date: '2026-04-16', title: "Physical Intelligence's new robot brain can figure out tasks it was never taught", source: 'TechCrunch', url: 'https://techcrunch.com/2026/04/16/physical-intelligence-a-hot-robotics-startup-says-its-new-robot-brain-can-figure-out-tasks-it-was-never-taught/', description: 'Physical Intelligence unveils π0.7, a robot AI model that performs tasks it was never trained on via compositional generalization. Valued at $5.6B with $11B funding round in progress.' },
  { date: '2026-04-17', title: 'NVIDIA Releases New Physical AI Models as Global Partners Unveil Next-Generation Robots', source: 'NVIDIA Newsroom', url: 'https://nvidianews.nvidia.com/news/nvidia-releases-new-physical-ai-models-as-global-partners-unveil-next-generation-robots', description: 'NVIDIA releases Isaac GR00T open models and Cosmos world models. Boston Dynamics, Franka Robotics, LG Electronics, and NEURA Robotics unveil robots built on NVIDIA stack.' },
  { date: '2026-04-18', title: 'Learn about the latest advances in physical AI at the Robotics Summit', source: 'The Robot Report', url: 'https://www.therobotreport.com/learn-about-latest-advances-physical-ai-robotics-summit/', description: 'The Robotics Summit & Expo previews physical AI sessions covering dexterous manipulation, foundation models for robots, and sim-to-real transfer breakthroughs.' },
  { date: '2026-04-19', title: 'The Physical AI Craze and Other Automation Trends to Watch in 2026', source: 'Manufacturing Dive', url: 'https://www.manufacturingdive.com/news/physical-ai-craze-2026-automation-trends-to-watch/810860/', description: '58% of enterprises already use physical AI per Deloitte survey, with 80% planning adoption within two years. Manufacturing Dive examines the hype vs. reality gap.' },
  { date: '2026-04-20', title: 'Humanoid Agile ONE Embodies Physical AI at Hannover Messe 2026', source: 'Agile Robots', url: 'https://www.agile-robots.com/en/news/detail/humanoid-agile-one-embodies-physical-ai-at-hannover-messe-2026/', description: 'Agile Robots showcases Agile ONE humanoid at Hannover Messe, greeting German Chancellor Friedrich Merz. CEO: "Physical AI is a catalyst redefining global industries."' },
  { date: '2026-04-21', title: 'DEEPX and Hyundai Motor Group Robotics LAB Partner to Develop Next-Generation Physical AI Compute Platform', source: 'RoboticsTomorrow', url: 'https://www.roboticstomorrow.com/news/2026/04/21/deepx-and-hyundai-motor-group-robotics-lab-partner-to-develop-next-generation-physical-ai-compute-platform-for-robotics/26451/', description: 'DEEPX and Hyundai partner to build ultra-low-power AI chips for robots. Physical AI semiconductor market projected to reach $123B by 2030.' },
  { date: '2026-04-22', title: 'Physical AI Market Set to Hit $15.24 Billion by 2032: Future Growth & Industry Trends', source: 'GlobeNewswire', url: 'https://www.globenewswire.com/news-release/2026/04/21/3278165/0/en/Physical-AI-Market-Set-to-Hit-15-24-Billion-by-2032-Future-Growth-Industry-Trends.html', description: 'Market research projects physical AI growing from $1.5B in 2026 to $15.24B by 2032 at 47.2% CAGR. Industrial automation leads with 56.7% CAGR for industrial robots.' },
  { date: '2026-04-23', title: 'Sony AI Robot Beats Elite Table Tennis Players — Breakthrough Published in Nature', source: 'Sony AI', url: 'https://ai.sony/news/sony-ai-announces-breakthrough-research-in-real-world-artificial-intelligence-and-robotics', description: 'Sony AI Project Ace robot beats 5 elite players, published on Nature cover. First real-world autonomous system competitive with professional-level humans in a sport.' },
  { date: '2026-04-24', title: 'The Mass Penalty Spiral: Why Humanoid Robotics Needs "Physical AI"', source: 'RoboticsTomorrow', url: 'https://www.roboticstomorrow.com/story/2026/04/the-mass-penalty-spiral-why-humanoid-robotics-needs-physical-ai/26416/', description: '"We are running 2026 intelligence on 1990s hardware." The mass penalty spiral explains why physical AI must be integrated directly into motion control hardware.' },
  { date: '2026-04-25', title: 'Physical AI Moves from Pilot Phase to Industrial Scale, Deloitte Says', source: 'Manila Times', url: 'https://www.manilatimes.net/2026/04/25/business/science-technology/physical-ai-moves-from-pilot-phase-to-industrial-scale-deloitte-says/2327993', description: 'Deloitte report confirms physical AI crossing from pilots to industrial-scale deployment, with humanoid robots entering factory floors across Asia and Europe.' },
  { date: '2026-04-26', title: 'Sereact Raises $110 Million to Scale AI Robotic Brain', source: 'PYMNTS', url: 'https://www.pymnts.com/news/investment-tracker/2026/sereact-raises-110-million-to-scale-ai-robotic-brain/', description: 'German startup Sereact raises $110M Series B for its Cortex 2.0 AI brain for robots. BMW and Daimler Trucks are customers. 53,000 tasks per human intervention recorded.' },
  { date: '2026-04-27', title: 'LG Electronics Teams Up with Nvidia to Boost Physical AI', source: 'Seoul Economic Daily', url: 'https://en.sedaily.com/finance/2026/04/27/lg-electronics-teams-up-with-nvidia-to-boost-physical-ai', description: 'LG Electronics CEO meets NVIDIA robotics director to integrate CLOiD home robot with NVIDIA Isaac platform, targeting autonomous AI home partner capabilities.' },
  { date: '2026-04-28', title: 'CVPR 2026 Showcases How AI Is Powering the Next Era of Robotics Innovation', source: 'RoboticsTomorrow', url: 'https://www.roboticstomorrow.com/news/2026/04/23/cvpr-2026-showcases-how-ai-is-powering-the-next-era-of-robotics-innovation/26472/', description: 'CVPR 2026 in Denver previewed: ManipArena competition, 75%+ of expo floor occupied by AI-robotics firms, global robotics funding exceeded $10.3B in 2025.' },
]

export function getArticleByDate(date: string): Article | undefined {
  return APRIL_ARTICLES.find((a) => a.date === date)
}
